// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#ifndef _DENEME_UI_H
#define _DENEME_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


// SCREEN: ui_Screenrate
void ui_Screenrate_screen_init(void);
extern lv_obj_t * ui_Screenrate;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Screenfull
void ui_Screenfull_screen_init(void);
extern lv_obj_t * ui_Screenfull;
extern lv_obj_t * ui_Logo1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPress
void ui_ScreenPress_screen_init(void);
extern lv_obj_t * ui_ScreenPress;
extern lv_obj_t * ui_Logo2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Pressbar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Label1;

// SCREEN: ui_Screendata
void ui_Screendata_screen_init(void);
extern lv_obj_t * ui_Screendata;
extern lv_obj_t * ui_Logo3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Spinner4;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_vollylogo_png);    // assets/vollylogo.png
LV_IMG_DECLARE(ui_img_780266359);    // assets/Adsız tasarım (1).png
LV_IMG_DECLARE(ui_img_994357186);    // assets/doluluk oranı.png
LV_IMG_DECLARE(ui_img_1464417411);    // assets/dolu (1).png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
