// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#include "ui.h"

// COMPONENT Doluluk

lv_obj_t * ui_Doluluk_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Doluluk;
    cui_Doluluk = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Doluluk, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(cui_Doluluk, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(cui_Doluluk, 40);
    lv_obj_set_y(cui_Doluluk, 18);
    lv_label_set_long_mode(cui_Doluluk, LV_LABEL_LONG_CLIP);
    lv_label_set_text(cui_Doluluk, "Doluluk\n");
    lv_obj_set_style_text_color(cui_Doluluk, lv_color_hex(0xE60A0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Doluluk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DOLULUK_NUM);
    children[UI_COMP_DOLULUK_DOLULUK] = cui_Doluluk;
    lv_obj_add_event_cb(cui_Doluluk, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Doluluk, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Doluluk_create_hook(cui_Doluluk);
    return cui_Doluluk;
}

