// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#include "ui.h"

void ui_comp_Doluluk_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Image2_create_hook(lv_obj_t * comp)
{
}
