// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#include "ui.h"

void ui_ScreenPress_screen_init(void)
{
    ui_ScreenPress = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPress, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScreenPress, lv_color_hex(0x3E3D42), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScreenPress, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo2 = lv_img_create(ui_ScreenPress);
    lv_img_set_src(ui_Logo2, &ui_img_vollylogo_png);
    lv_obj_set_width(ui_Logo2, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Logo2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Logo2, -9);
    lv_obj_set_y(ui_Logo2, -130);
    lv_obj_set_align(ui_Logo2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Logo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo2, 100);

    ui_Label1 = lv_label_create(ui_ScreenPress);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Pressleme islemi yapiliyor.\n       Lutfen bekleyiniz.");

    ui_Pressbar = lv_bar_create(ui_ScreenPress);
    lv_bar_set_value(ui_Pressbar, 85, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Pressbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Pressbar, 207);
    lv_obj_set_height(ui_Pressbar, 23);
    lv_obj_set_x(ui_Pressbar, 2);
    lv_obj_set_y(ui_Pressbar, 60);
    lv_obj_set_align(ui_Pressbar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Pressbar, lv_color_hex(0x0CC6DB), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pressbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Pressbar, lv_color_hex(0x0073FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Pressbar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_Label1 = ui_Label1;

}
