// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#include "ui.h"

void ui_Screenfull_screen_init(void)
{
    ui_Screenfull = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screenfull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screenfull, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screenfull, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screenfull, lv_color_hex(0x3E3D42), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screenfull, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Screenfull, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo1 = lv_img_create(ui_Screenfull);
    lv_img_set_src(ui_Logo1, &ui_img_vollylogo_png);
    lv_obj_set_width(ui_Logo1, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Logo1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Logo1, -9);
    lv_obj_set_y(ui_Logo1, -130);
    lv_obj_set_align(ui_Logo1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Logo1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo1, 100);

    ui_Image3 = lv_img_create(ui_Screenfull);
    lv_img_set_src(ui_Image3, &ui_img_1464417411);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 177
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 183
    lv_obj_set_x(ui_Image3, 6);
    lv_obj_set_y(ui_Image3, 67);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 135);

    ui_Label4 = lv_label_create(ui_Screenfull);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 8);
    lv_obj_set_y(ui_Label4, -109);
    lv_obj_set_align(ui_Label4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label4, "Cop kutusu tamamen doludur\n        Lutfen cop atmayiniz");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}
