// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: deneme

#include "ui.h"

void ui_Screendata_screen_init(void)
{
    ui_Screendata = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screendata, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screendata, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screendata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screendata, lv_color_hex(0x3E3D42), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screendata, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo3 = lv_img_create(ui_Screendata);
    lv_img_set_src(ui_Logo3, &ui_img_vollylogo_png);
    lv_obj_set_width(ui_Logo3, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_Logo3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Logo3, -9);
    lv_obj_set_y(ui_Logo3, -130);
    lv_obj_set_align(ui_Logo3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Logo3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Logo3, 100);

    ui_Label3 = lv_label_create(ui_Screendata);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Data bekleniyor...");

    ui_Spinner4 = lv_spinner_create(ui_Screendata, 1000, 90);
    lv_obj_set_width(ui_Spinner4, 43);
    lv_obj_set_height(ui_Spinner4, 43);
    lv_obj_set_x(ui_Spinner4, 2);
    lv_obj_set_y(ui_Spinner4, 56);
    lv_obj_set_align(ui_Spinner4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner4, lv_color_hex(0x557BCA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner4, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
